### ISSUE TITLE
Unix time wording

### ISSUE THREAD

**Issue by wangjie-agora** [AgoraDoc/agora-style-guide#17]
Form Bill:

> While I get myself organized around reviewing the style guide, one issue that came up is the format for Unix time. This should be documented. Keith says this has been discussed in the past and that what you are using is "Unix format (time in seconds since 1970) in UTC." Should it maybe be "Unix time (in seconds since 1 January 1970) in UTC"?

**Comment by mst3k4ever** [comment]
Hello! I will consult with Keith to make sure it is absolutely correct and then add this as soon as I can. Cheers.

**Comment by mst3k4ever** [comment]
PS: mst3k4ever is Bill.  :)

**Comment by DITAWriter** [comment]
I agree with Bill that "Unix time (in seconds since 1 January 1970) in UTC" is the better phrasing, especially as "Unix time" is the most widely used term in English.
I know I had a similar debate back in the March/April timeframe (I think before we got serious with revamping the Stlke Guide), and the wording we came up with was something of a compromise. After doing some research, I agree with Bill's stance on the phrasing of the term.
Cheers!
    On Thursday, September 24, 2020, 12:33:54 a.m. EDT, mst3k4ever <notifications@github.com> wrote:  
 
 


PS: mst3k4ever is Bill. :)
