### ISSUE TITLE
Question about Agora-related naming conventions

### ISSUE THREAD

**Issue by wangjie-agora** [AgoraDoc/agora-style-guide#6]
In the [Agora-related naming conventions](https://agoradoc-style-guide.readthedocs.io/en/latest/references.html#agora-related-naming-conventions) section, there's this rule: 

> When not prefaced by “Agora”, do not append an SDK with a “the”. For example, “RTC SDK”.

Why do we drop "the" when omitting Agora? @DITAWriter

**Comment by DITAWriter** [comment]
That's a good question actually. I don't think this particular rule in its current form holds up, because as I dig into the idea of dropping "the" before a product name, it is more generally a convention that would also apply to an SDK when prefaced by "Agora". So the rule really ought to apply to both forms, and not just to when "Agora" is dropped. It is more a marketing than a technical documentation convention however, and it is the reason why you never see "the" added when referring to some software products, such as "get me a copy of the MS Word" or "that program does not run on the Windows 10". Personally I have never much liked this "rule", and if we decide to drop it from our house style, I would not mind in the least.
Cheers!
    On Wednesday, June 3, 2020, 01:24:38 a.m. EDT, wangjie-agora <notifications@github.com> wrote:  
 
 


In the Agora-related naming conventions section, there's this rule:


When not prefaced by “Agora”, do not append an SDK with a “the”. For example, “RTC SDK”.


Why do we drop "the" when omitting Agora? @DITAWriter

**Comment by wangjie-agora** [comment]
We mostly think of the SDKs as common nouns, not product names. On DP, a product would be Real-time Messaging, which uses the Real-time Messaging SDK to achieve its functions.

**Comment by Rebeccacy** [comment]
MS Word or Windows are such widely used terms that appending them with "the" seems really weird and redundant. But for SDK names it sounds more natural to have "the" appended.

**Comment by DITAWriter** [comment]
It is our house style and we can do whatever we want to. The best thing to do however is to be consistent. If we like the idea of adding "the" before the name of an SDK, then let's make it a house rule. My research shows that there is no definite answer to this style question, so we just have to decide for ourselves and then stick to it.
We can drop the "the" before "Agora", but keep it when describing an SDK not preceded by the company name. If that works for you, then let's make it a rule in the Style Guide.
Cheers!
    On Sunday, June 7, 2020, 09:19:28 p.m. EDT, Rebeccacy <notifications@github.com> wrote:  
 
 


MS Word or Windows are such widely used terms that appending them with "the" seems really weird and redundant. But for SDK names it sounds more natural to have "the" appended.
